config/routes.rb
Blueprint::Application.routes.draw do

  devise_for :users

  scope "(:locale)", :locale => /en|fr/ do
    resources :pages do
      collection do
        get :welcome
      end
    end
    authenticated :user do
      resources :users
    end
  end

  root :to => 'pages#welcome', :as => 'home'

end

app/models/user.rb
# Member user model
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :name, :password, :password_confirmation, :remember_me

  validates :email, :uniqueness => true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => 'invalid email format'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :set_locale_from_url

  def default_url_options(options={})
    { :locale => I18n.locale}
  end

  private

  def set_locale_from_url
    I18n.locale = params[:locale] ||= I18n.default_locale
  end

end

app/controllers/pages_controller.rb
class PagesController < HighVoltage::PagesController
  layout 'application'
end

app/controllers/users_controller.rb
# Member users controller
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def icon_class(name)
    '<i class="' + name + '"></i>'
  end

  def icon_with_label(icon, label)
    raw(icon_class(icon) + ' ' + label)
  end

  # Nested forms -add field set
  def link_to_add_fields(name, f, association, classes = '')
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "Application.add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")", :class => "#{classes}")
  end

  # Nested forms -remove field set
  def link_to_remove_fields(name, f, classes = '') 
    f.hidden_field(:_destroy) + link_to_function(name, "Application.remove_fields(this)", :class => "#{classes}")
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def quantity_remaining(item)
    "#{item.quantity_remaining} - #{item.lot_quantity} Remaining."
  end

  def remaining(item)
    "#{item.quantity_remaining}/#{item.lot_quantity} Left"
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= Settings[:title]
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
%body
  .container
    = render 'shared/navbar'
    .container-fluid
      .row-fluid
        .span12
          - if alert
            .alert.alert-error.fade.in{:data => {:alert => 'alert'} }
              %a{:class => "close", :data => {:dismiss => 'alert'}, :href => "#"} ×
              %p= alert
          - if notice
            .alert.alert-success.fade.in{:data => {:alert => 'alert'} }
              %a{:class => "close", :data => {:dismiss => 'alert'}, :href => "#"} ×
              %p= notice
          = yield
  = render 'shared/footer'

app/views/mailroom/_confirm_order.en.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    :css
      table.bottomBorder { border-collapse:collapse; }
      table.bottomBorder td, table.bottomBorder th { border-bottom:1px solid black;padding:5px; }
  %body
  %h1 Order Confirmation

  %p
    %b Customer Name:
    = @customer_order.ship_to_name
  %p
    %b Email:
    = @customer_order.email
  %hr
  - if @customer_order.ship_to_address == @customer_order.billing_address
    %table
      %thead
        %tr
          %th Shipping Address:
      %tbody
        %tr
          %td= @customer_order.ship_to_name
        %tr
          %td= @customer_order.ship_to_address
        %tr
          %td= "#{@customer_order.ship_to_city}, #{@customer_order.ship_to_province} #{@customer_order.ship_to_postal_code}"
  - else
    %table{:style => 'width: 45%; float: right;'}
      %thead
        %tr
          %th Billing Address:
      %tbody
        %tr
          %td= @customer_order.billing_name
        %tr
          %td= "#{@customer_order.billing_city}, #{@customer_order.billing_province}"
    %table{:style => 'width: 45%;'}
      %thead
        %tr
          %th Shipping Address:
      %tbody
        %tr
          %td= @customer_order.ship_to_name
        %tr
          %td= @customer_order.ship_to_address
        %tr
          %td= "#{@customer_order.ship_to_city}, #{@customer_order.ship_to_province} #{@customer_order.ship_to_postal_code}"

  %hr
  %table.bottomBorder
    %thead
      %tr
        %th SKU
        %th Description
        %th Sale Price
        %th Quantity
        %th Extended
    %tbody
      - @customer_order.customer_order_items.each do |customer_order_item|
        %tr
          %td= customer_order_item.sku
          %td= customer_order_item.description
          %td= number_to_currency customer_order_item.sale_price
          %td= customer_order_item.quantity
          %td= number_to_currency customer_order_item.extended_price
      %tr
        %td{:colspan => 4} Subtotal:
        %td= number_to_currency @customer_order.subtotal

app/views/mailroom/_confirm_order.fr.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    :css
      table.bottomBorder { border-collapse:collapse; }
      table.bottomBorder td, table.bottomBorder th { border-bottom:1px solid black;padding:5px; }
  %body
  %h1 Order Confirmation

  %p
    %b Customer Name:
    = @customer_order.ship_to_name
  %p
    %b Email:
    = @customer_order.email
  %hr
  - if @customer_order.ship_to_address == @customer_order.billing_address
    %table
      %thead
        %tr
          %th Shipping Address:
      %tbody
        %tr
          %td= @customer_order.ship_to_name
        %tr
          %td= @customer_order.ship_to_address
        %tr
          %td= "#{@customer_order.ship_to_city}, #{@customer_order.ship_to_province} #{@customer_order.ship_to_postal_code}"
  - else
    %table{:style => 'width: 45%; float: right;'}
      %thead
        %tr
          %th Billing Address:
      %tbody
        %tr
          %td= @customer_order.billing_name
        %tr
          %td= "#{@customer_order.billing_city}, #{@customer_order.billing_province}"
    %table{:style => 'width: 45%;'}
      %thead
        %tr
          %th Shipping Address:
      %tbody
        %tr
          %td= @customer_order.ship_to_name
        %tr
          %td= @customer_order.ship_to_address
        %tr
          %td= "#{@customer_order.ship_to_city}, #{@customer_order.ship_to_province} #{@customer_order.ship_to_postal_code}"

  %hr
  %table.bottomBorder
    %thead
      %tr
        %th SKU
        %th Description
        %th Sale Price
        %th Quantity
        %th Extended
    %tbody
      - @customer_order.customer_order_items.each do |customer_order_item|
        %tr
          %td= customer_order_item.sku
          %td= customer_order_item.description
          %td= number_to_currency customer_order_item.sale_price
          %td= customer_order_item.quantity
          %td= number_to_currency customer_order_item.extended_price
      %tr
        %td{:colspan => 4} Subtotal:
        %td= number_to_currency @customer_order.subtotal

app/views/mailroom/_confirm_shipment.en.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    :css
      table.bottomBorder { border-collapse:collapse; }
      table.bottomBorder td, table.bottomBorder th { border-bottom:1px solid black;padding:5px; }
  %body
  %h1 Shipment Confirmation

  %p= "Your order has been shipped via #{@shipment.shipping_service.carrier_service}.  Your tracking number is #{@shipment.tracking_number}."

  %p
    %b Customer Name:
    = @shipment.customer_order.ship_to_name
  %p
    %b Email:
    = @shipment.customer_order.email
  %hr
  - if @shipment.customer_order.ship_to_address == @shipment.customer_order.billing_address
    %table
      %thead
        %tr
          %th Shipping Address:
      %tbody
        %tr
          %td= @shipment.customer_order.ship_to_name
        %tr
          %td= @shipment.customer_order.ship_to_address
        %tr
          %td= "#{@shipment.customer_order.ship_to_city}, #{@shipment.customer_order.ship_to_province} #{@shipment.customer_order.ship_to_postal_code}"
  - else
    %table{:style => 'width: 45%; float: right;'}
      %thead
        %tr
          %th Billing Address:
      %tbody
        %tr
          %td= @shipment.customer_order.billing_name
        %tr
          %td= "#{@shipment.customer_order.billing_city}, #{@shipment.customer_order.billing_province}"
    %table{:style => 'width: 45%;'}
      %thead
        %tr
          %th Shipping Address:
      %tbody
        %tr
          %td= @shipment.customer_order.ship_to_name
        %tr
          %td= @shipment.customer_order.ship_to_address
        %tr
          %td= "#{@shipment.customer_order.ship_to_city}, #{@shipment.customer_order.ship_to_province} #{@shipment.customer_order.ship_to_postal_code}"

  %hr
  %table.bottomBorder
    %thead
      %tr
        %th SKU
        %th Description
        %th Sale Price
        %th Quantity
        %th Extended
    %tbody
      - @shipment.customer_order.customer_order_items.each do |customer_order_item|
        %tr
          %td= customer_order_item.sku
          %td= customer_order_item.description
          %td= number_to_currency customer_order_item.sale_price
          %td= customer_order_item.quantity
          %td= number_to_currency customer_order_item.extended_price
      %tr
        %td{:colspan => 4} Subtotal:
        %td= number_to_currency @shipment.customer_order.subtotal

app/views/mailroom/confirm_order.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
	</head>
	<body>
		<%= render :partial => "confirm_order", :object => @customer_order %>
	</body>
</html>

app/views/mailroom/confirm_shipment.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
	</head>
	<body>
		<%= render :partial => "confirm_shipment", :object => @shipment %>
	</body>
</html>

app/views/pages/welcome.html.haml
%h1 MVE Solutions Web Blueprint

app/views/shared/_edit_links.html.haml
= link_to 'Back', back_path, :class => 'btn btn-mini'

app/views/shared/_errors.html.haml
- if f.object.errors.present?
  .alert.alert-error.fade.in{:data => {:alert => 'alert'} }
    %a{:class => "close", :data => {:dismiss => 'alert'}, :href => "#"} ×
    = f.error_notification
    %i.text-error= f.object.errors.full_messages.join('. ')

app/views/shared/_footer.html.haml
.footer.row-fluid

  %p.pull-right.hidden-phone= link_to "Web Master", "mailto:cfavreau@mvesolutions.com?subject=website"

  %p.pull-left
    = image_tag("solutions.logo.gif", :style => "width: 35px; vertical-align: middle; margin-right: 5px;", :alt => "MVE Solutions Stylized Acorn Logo")
    = link_to "MVE Solutions Inc.", "http://mvesolutions.com"
    &copy; 2013-2014

app/views/shared/_index_links.html.haml
- new_path = new_path || nil
- if new_path
  = link_to label_new, new_path, :class => 'btn btn-info'

app/views/shared/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar{:data => {:toggle => "collapse", :target => ".nav-collapse"}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to Settings.brand, nil, :class => 'brand'

      %ul.nav.pull-right
        %li= link_to 'Sign Up', new_user_registration_path

        - if user_signed_in?
          %li.dropdown
            %a#current-user.dropdown-toggle{:role => :button, :data => {:toggle => "dropdown", :target => '#'}}
              = current_user.email.split('@').first
              %span.caret
            %ul.dropdown-menu{:role => :menu, 'aria-labeledby' => 'current-user'}
              %li.menu_list{:role => :menuitem}= link_to 'Change Password', edit_user_registration_path
              %li.menu_list{:role => :menuitem}= link_to 'Sign Out', destroy_user_session_path, :method => 'delete'
        - else
          %li= link_to 'Sign In', new_user_session_path

        - if I18n.locale == I18n.default_locale
          %li= link_to icon_with_label('icon-globe', "français"), :locale=>'fr'
        - else
          %li= link_to icon_with_label('icon-globe', "English"), :locale=>'en'

      .nav-collapse.collapse
        %ul.nav
          %li= link_to I18n.t('navbar.home'), home_path
          = render 'shared/navbar_admin'

app/views/shared/_navbar_admin.html.haml
- if user_signed_in?
  %li#user.dropdown
    %a.dropdown-toggle{:'data-toggle' => 'dropdown'}
      = t('navbar_user.administration')
      <span class="caret"></span></a>
    %ul.dropdown-menu
      %li.menu-list= link_to I18n.t('navbar_admin.user'), users_path

app/views/shared/_new_links.html.haml
= link_to 'Back', back_path, :class => 'btn btn-mini'

app/views/shared/_show_links.html.haml
.well.well-small
  = link_to 'Back', back_path, :class => 'btn btn-mini'

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = render partial: 'shared/errors', locals: {f: f}

  .form-inputs
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
    = f.input :name

  .form-actions.control-group
    = f.submit :class => 'btn btn-info'

app/views/users/edit.html.haml
%h1 Editing User's

= render 'form'

= render :partial => 'shared/edit_links', :locals => {:back_path => users_path}

app/views/users/index.html.haml
%h1 Listing Users

%table.table.table-striped
  %thead
    %tr
      %th Email
      %th Name
  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= user.name
        %td
          = link_to 'Show', user_path(user), :class => 'btn btn-mini'
          = link_to 'Edit', edit_user_path(user), :class => 'btn btn-mini'
          = link_to 'Destroy', user_path(user), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini btn-danger'

%br

= render :partial => 'shared/index_links', :locals => {:label_new => "New User", :new_path => new_user_path}

app/views/users/new.html.haml
%h1 New User

= render 'form'

= render :partial => 'shared/new_links', :locals => {:back_path =>  users_path}

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.haml
%p#notice= notice


%fieldset
  %legend Users
  %p
    %b Email:
    = @user.email
  %p
    %b Name:
    = @user.name

  = render :partial => 'shared/show_links', :locals => {:back_path => users_path}